# Generated by Django 2.2.1 on 2019-05-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='booker')),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
