# Generated by Django 2.2.1 on 2019-05-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytle', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='booker/book_covers')),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='next_month_app.Archive')),
            ],
            options={
                'verbose_name_plural': 'books',
            },
        ),
    ]
