# Generated by Django 2.2.1 on 2019-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_month_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name_plural': 'books'},
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='tytle',
            new_name='name',
        ),
        migrations.AddField(
            model_name='archive',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='NextBook',
        ),
    ]
