# Generated by Django 2.2.1 on 2019-05-27 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('next_month_app', '0002_auto_20190526_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentBook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='next_month_app.Archive')),
            ],
        ),
    ]
